# Generated by Django 5.0.6 on 2024-07-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_milage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ('-year',), 'verbose_name': 'пробег', 'verbose_name_plural': 'пробеги'},
        ),
    ]
